// ── $5K CHALLENGE CONSTANTS ───────────────────────────────────────────────

export const CHALLENGE = {
  startDate: '2026-04-10',
  endDate: '2026-05-31',
  startingCapital: 5000,
  targetCapital: 15000,
}

export const TIERS = [
  {
    name: 'SURVIVAL',
    range: [0, 6500],
    riskPct: 0.015,
    maxPositions: 2,
    strategies: ['long_call', 'long_put', 'call_debit_spread', 'put_debit_spread'],
    rules: ['No earnings plays', 'Minimum 2:1 R:R', 'Debit spreads and single legs only', 'No overnight unless forced'],
    color: '#ef4444',
    tag: 'SURVIVE',
  },
  {
    name: 'GROWTH',
    range: [6500, 9000],
    riskPct: 0.02,
    maxPositions: 3,
    strategies: ['long_call', 'long_put', 'call_debit_spread', 'put_debit_spread', 'call_credit_spread', 'put_credit_spread'],
    rules: ['Wider spreads OK', 'Swing trades allowed', '1 overnight position OK', 'Minimum 2.5:1 R:R'],
    color: '#f59e0b',
    tag: 'GROW',
  },
  {
    name: 'ACCELERATE',
    range: [9000, 12000],
    riskPct: 0.02,
    maxPositions: 4,
    strategies: ['long_call', 'long_put', 'call_debit_spread', 'put_debit_spread', 'call_credit_spread', 'put_credit_spread', 'iron_condor', 'straddle', 'strangle', 'butterfly', 'calendar'],
    rules: ['Full toolkit unlocked', '5% asymmetric bets OK on A+ setups', 'Lock profits at 3:1+', 'Scale into winners'],
    color: '#00d4aa',
    tag: 'ACCELERATE',
  },
  {
    name: 'PROTECT',
    range: [12000, Infinity],
    riskPct: 0.015,
    maxPositions: 3,
    strategies: ['long_call', 'long_put', 'call_debit_spread', 'put_debit_spread', 'call_credit_spread', 'put_credit_spread', 'iron_condor', 'butterfly'],
    rules: ['High-conviction only', 'Trailing stops required', 'Protect gains — no hero trades', 'Reduce size if on tilt'],
    color: '#a855f7',
    tag: 'PROTECT',
  },
]

export const STRATEGIES = [
  { key: 'long_call', label: 'Long Call', direction: 'bullish', type: 'debit' },
  { key: 'long_put', label: 'Long Put', direction: 'bearish', type: 'debit' },
  { key: 'call_debit_spread', label: 'Call Debit Spread', direction: 'bullish', type: 'debit' },
  { key: 'put_debit_spread', label: 'Put Debit Spread', direction: 'bearish', type: 'debit' },
  { key: 'call_credit_spread', label: 'Call Credit Spread', direction: 'bearish', type: 'credit' },
  { key: 'put_credit_spread', label: 'Put Credit Spread', direction: 'bullish', type: 'credit' },
  { key: 'iron_condor', label: 'Iron Condor', direction: 'neutral', type: 'credit' },
  { key: 'straddle', label: 'Straddle', direction: 'neutral', type: 'debit' },
  { key: 'strangle', label: 'Strangle', direction: 'neutral', type: 'debit' },
  { key: 'butterfly', label: 'Butterfly', direction: 'neutral', type: 'debit' },
  { key: 'calendar', label: 'Calendar Spread', direction: 'neutral', type: 'debit' },
]

export const SETUP_TYPES = [
  { key: 'momentum_breakout', label: 'Momentum Breakout', icon: '▲' },
  { key: 'failed_breakdown', label: 'Failed Breakdown', icon: '◇' },
  { key: 'vol_crush', label: 'Volatility Crush', icon: '◈' },
  { key: 'episodic_pivot', label: 'Episodic Pivot', icon: '★' },
  { key: 'mean_reversion', label: 'Mean Reversion', icon: '↩' },
  { key: 'sr_rejection', label: 'S/R Rejection', icon: '⊘' },
  { key: 'other', label: 'Other', icon: '◎' },
]

export const REVIEW_CRITERIA = [
  { key: 'thesisCorrect', label: 'Thesis Correct', weight: 2 },
  { key: 'entryTiming', label: 'Entry Timing', weight: 2 },
  { key: 'positionSized', label: 'Position Sized', weight: 2 },
  { key: 'stopHonored', label: 'Stop Honored', weight: 3 },
  { key: 'exitTiming', label: 'Exit Timing', weight: 2 },
  { key: 'emotionFree', label: 'Emotion Free', weight: 3 },
  { key: 'rulesFollowed', label: 'Rules Followed', weight: 3 },
  { key: 'riskManaged', label: 'Risk Managed', weight: 2 },
  { key: 'journaled', label: 'Journaled', weight: 1 },
]

export const TIMEFRAME_MODES = {
  scalp: {
    key: 'scalp',
    label: 'Scalp',
    tag: '0-2 DTE',
    color: '#ff6b6b',
    dteRange: [0, 2],
    deltaRange: [0.55, 0.70],
    description: 'Intraday to next-day expiration. Speed and precision. Momentum-driven.',
    weights: { trend: 0.5, momentum: 1.8, volume: 1.6, iv: 0.3 },
    strategies: ['long_call', 'long_put', 'call_debit_spread', 'put_debit_spread'],
    rules: ['Tight stops — 30-50% max loss', 'Take profits at 50-100%', 'No holding through close unless planned', 'Volume confirmation required'],
    keyMetrics: ['Momentum Score', 'Volume Ratio', 'RSI', 'Intraday Trend'],
    idealSetups: ['momentum_breakout', 'sr_rejection'],
    warning: null,
  },
  swing: {
    key: 'swing',
    label: 'Swing',
    tag: '3-14 DTE',
    color: '#00d4aa',
    dteRange: [3, 14],
    deltaRange: [0.45, 0.60],
    description: 'Multi-day holds. Balanced scoring across all factors. DEFAULT MODE.',
    weights: { trend: 1.0, momentum: 1.0, volume: 1.0, iv: 1.0 },
    strategies: ['long_call', 'long_put', 'call_debit_spread', 'put_debit_spread', 'call_credit_spread', 'put_credit_spread'],
    rules: ['Hold 2-10 days typically', 'Trail stops after 2:1', 'Respect the daily close', 'Scale out at targets'],
    keyMetrics: ['Composite Score', 'Trend Score', 'RS 3M', 'HV Rank'],
    idealSetups: ['momentum_breakout', 'failed_breakdown', 'mean_reversion', 'sr_rejection'],
    warning: null,
  },
  position: {
    key: 'position',
    label: 'Position',
    tag: '14-45 DTE',
    color: '#00ccff',
    dteRange: [14, 45],
    deltaRange: [0.40, 0.55],
    description: 'Multi-week holds. Trend and IV environment dominate. Patient entries.',
    weights: { trend: 1.5, momentum: 0.7, volume: 0.5, iv: 1.3 },
    strategies: ['long_call', 'long_put', 'call_debit_spread', 'put_debit_spread', 'call_credit_spread', 'put_credit_spread', 'iron_condor', 'butterfly', 'calendar'],
    rules: ['Trend must be established', 'IV rank matters more', 'Wider stops OK', 'Roll if needed'],
    keyMetrics: ['Trend Score', 'HV Rank', 'ADX', 'Stage'],
    idealSetups: ['momentum_breakout', 'vol_crush', 'episodic_pivot'],
    warning: null,
  },
  leaps: {
    key: 'leaps',
    label: 'LEAPS',
    tag: '90+ DTE',
    color: '#a855f7',
    dteRange: [90, 730],
    deltaRange: [0.60, 0.80],
    description: 'Long-term directional. Trend is everything. Buy on IV dips.',
    weights: { trend: 2.0, momentum: 0.3, volume: 0.2, iv: 1.5 },
    strategies: ['long_call', 'long_put', 'call_debit_spread', 'put_debit_spread'],
    rules: ['Only Stage 2 confirmed uptrends', 'Buy when IV rank < 30', 'Deep ITM delta 0.60-0.80', 'Size smaller — time is your edge'],
    keyMetrics: ['Trend Score', 'Stage', 'IV Rank', 'RS 3M'],
    idealSetups: ['momentum_breakout', 'episodic_pivot'],
    warning: 'LEAPS require strong conviction and are capital-intensive. Size accordingly.',
  },
}

export const DEBRIEF_CHECKLIST = {
  premarkt: [
    'Reviewed overnight futures and macro',
    'Checked watchlist for gaps/news',
    'Set alerts at key levels',
    'Reviewed open positions and stops',
  ],
  execution: [
    'Followed pre-trade checklist before entry',
    'Position sized per tier rules',
    'Entered at planned level (no chasing)',
    'Set stop immediately after fill',
  ],
  postmarket: [
    'Logged all trades with thesis',
    'Completed trade reviews',
    'Updated equity curve',
    'Journaled lessons learned',
  ],
}

export const MOOD_STATES = [
  { key: 'locked', label: 'Locked In', emoji: '🎯', color: '#00d4aa' },
  { key: 'confident', label: 'Confident', emoji: '💪', color: '#22c55e' },
  { key: 'neutral', label: 'Neutral', emoji: '😐', color: '#f59e0b' },
  { key: 'shaky', label: 'Shaky', emoji: '😟', color: '#ef4444' },
  { key: 'tilted', label: 'Tilted', emoji: '🔥', color: '#ff2a44' },
]

export const PLAYBOOK_SETUPS = [
  {
    name: 'Momentum Breakout',
    type: 'long',
    winRate: '55-65%',
    rrTarget: '3:1',
    entry: 'Break above resistance with 1.3x+ volume, RSI 55-70, Stage 2 confirmed',
    timeframe: 'Swing (3-14 DTE) or Position (14-45 DTE)',
    sizing: 'Full size if A+ grade, half size if A',
    ivRule: 'Enter when HV Rank < 50 for debit plays',
    edge: 'Momentum + trend alignment + volume confirmation = highest probability setup',
  },
  {
    name: 'Failed Breakdown Recovery',
    type: 'long',
    winRate: '50-60%',
    rrTarget: '2.5:1',
    entry: 'Price reclaims support after failed breakdown, volume returns, RS improving',
    timeframe: 'Swing (5-14 DTE)',
    sizing: 'Half size initial, add on confirmation',
    ivRule: 'IV often elevated after breakdown — consider spreads',
    edge: 'Trapped shorts provide fuel. Counter-trend but with momentum shift.',
  },
  {
    name: 'IV Crush Play',
    type: 'neutral',
    winRate: '60-70%',
    rrTarget: '1.5:1',
    entry: 'HV Rank > 70, ADX < 20, sell iron condor at 1 SD wings',
    timeframe: 'Position (14-30 DTE)',
    sizing: 'Standard size, defined risk',
    ivRule: 'Only when IV Rank > 70 AND ADX < 20',
    edge: 'Mean reversion of volatility. Time decay + vol crush = double tailwind.',
  },
  {
    name: 'Episodic Pivot',
    type: 'long',
    winRate: '45-55%',
    rrTarget: '4:1',
    entry: 'Gap up on earnings/news with 3x+ volume, immediate follow-through',
    timeframe: 'Swing (5-14 DTE) or LEAPS for conviction',
    sizing: 'Smaller size — asymmetric R:R compensates',
    ivRule: 'IV will be high post-event — use spreads or wait for crush',
    edge: 'Institutional re-rating. The setup IS the catalyst. Ride the momentum.',
  },
  {
    name: 'Mean Reversion',
    type: 'long',
    winRate: '55-65%',
    rrTarget: '2:1',
    entry: 'RSI < 28 at key support level, oversold bounce setup',
    timeframe: 'Scalp (0-2 DTE) or Swing (3-7 DTE)',
    sizing: 'Half size — counter-trend is inherently riskier',
    ivRule: 'IV often elevated at extremes — consider selling premium',
    edge: 'Rubber band effect at support. Quick snap-back when selling exhausts.',
  },
  {
    name: 'S/R Rejection Short',
    type: 'short',
    winRate: '50-60%',
    rrTarget: '2.5:1',
    entry: 'Price rejected at resistance with declining RS, Stage 3-4, volume on rejection',
    timeframe: 'Swing (5-14 DTE)',
    sizing: 'Standard size with defined-risk puts or put spreads',
    ivRule: 'Puts are cheaper when IV is low — better entry',
    edge: 'Distribution phase. Smart money selling into retail buying. Gravity wins.',
  },
]

// Design tokens for the challenge module
export const CC = {
  bg: '#070b12',
  surface: '#0c1219',
  surfaceAlt: '#111a25',
  border: '#1a2535',
  borderHi: '#243247',
  text: '#c8d6e5',
  textBright: '#e8f0f8',
  textMuted: '#5a6a7e',
  accent: '#00d4aa',
  profit: '#22c55e',
  loss: '#ef4444',
  warning: '#f59e0b',
  blue: '#00ccff',
  purple: '#a855f7',
  gold: '#ffcc00',
}

export const FONTS = {
  heading: "'Chakra Petch', sans-serif",
  mono: "'JetBrains Mono', monospace",
  body: "'DM Sans', sans-serif",
}
